version: '3.3'
services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    restart: always
    expose:
      - '27017'
  app:
    image: lytecode/game-services
    expose:
      - '5000'
    links:
      - mongo
    depends_on:
      - mongo
    restart: always
    environment:
      MONGO_URL: mongo

  lbapp:
    image: dockercloud/haproxy
    links:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '5000:80'

volumes:
  mongo-data: {}
